[package]
name = "cratebase-auth"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
serde.workspace = true
rand.workspace = true
sha2 = "0.10"
thiserror.workspace = true

[dependencies.argon2]
version = "0.5"

[dependencies.rand_core]
version = "0.6"
features = ["getrandom"]

[dependencies.jsonwebtoken]
version = "9"
