#!/usr/bin/env bun
/**
 * Turns a Cratebase "schema as code" document into a single `.d.ts`-style
 * file with one `interface` per non-system collection.
 *
 * The input is exactly what `GET /api/collections` returns (an
 * `{items: [...]}` page), what `PUT /api/collections/import` and
 * `POST /api/schema/apply` accept (`{collections: [...]}`), a bare array
 * of collection objects, or a live server URL to fetch that page from
 * directly — see `loadCollections` below. Field types follow
 * `crates/core/src/field.rs`'s `FieldKind` variants one-for-one (see
 * `TYPE_MAP`), so a change to that enum is the only place this mapping
 * needs to catch up.
 *
 * This is a build-time script for a *project's own* pipeline, not part
 * of Cratebase's server or admin dashboard — it has no dependency on
 * either. Usage:
 *
 * ```sh
 * bun run src/codegen.ts ./schema.json ./src/cratebase-types.d.ts
 * bun run src/codegen.ts https://api.example.com --token <superuser-jwt> -o types.d.ts
 * ```
 */

interface FieldDoc {
  name: string;
  type: string;
  required?: boolean;
  system?: boolean;
  maxSelect?: number;
}

interface CollectionDoc {
  name: string;
  type?: string;
  system?: boolean;
  fields?: FieldDoc[];
}

/** One-for-one with `FieldKind`'s variants in `crates/core/src/field.rs`. */
const SCALAR_TYPES: Record<string, string> = {
  text: "string",
  editor: "string",
  email: "string",
  url: "string",
  password: "string",
  date: "string",
  autodate: "string",
  number: "number",
  bool: "boolean",
  json: "unknown",
  vector: "number[]",
  geoPoint: "{ lon: number; lat: number }",
};

/** `select`, `file` and `relation` are single- or multi-valued depending
 * on `maxSelect`, unlike every other kind. */
const MULTI_VALUE_TYPES: Record<string, string> = {
  select: "string",
  file: "string",
  relation: "string",
};

function tsType(field: FieldDoc): string {
  if (field.type in MULTI_VALUE_TYPES) {
    const base = MULTI_VALUE_TYPES[field.type];
    return (field.maxSelect ?? 1) > 1 ? `${base}[]` : base;
  }
  return SCALAR_TYPES[field.type] ?? "unknown";
}

/** `posts` -> `PostsRecord`, `push-subscriptions` -> `PushSubscriptionsRecord`. */
function pascalCase(name: string): string {
  const cleaned = name.replace(/[^A-Za-z0-9]+/g, " ").trim();
  return cleaned
    .split(/\s+/)
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join("");
}

/** A property key that needs no quoting is emitted bare; anything else
 * (a field named with a hyphen, say) is a quoted string literal key. */
function propertyKey(name: string): string {
  return /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(name) ? name : JSON.stringify(name);
}

function generateInterface(collection: CollectionDoc): string {
  const interfaceName = `${pascalCase(collection.name)}Record`;
  const fields = collection.fields ?? [];
  const lines: string[] = [
    `/** \`${collection.name}\` (${collection.type ?? "base"}). Generated by @cratebase/schema-codegen — do not edit by hand. */`,
    `export interface ${interfaceName} {`,
  ];
  for (const field of fields) {
    const optional = field.required ? "" : "?";
    lines.push(`  ${propertyKey(field.name)}${optional}: ${tsType(field)};`);
  }
  lines.push("}");
  return lines.join("\n");
}

/** Extract the collection array from any of the shapes described in the
 * module doc. */
function extractCollections(doc: unknown): CollectionDoc[] {
  if (Array.isArray(doc)) return doc as CollectionDoc[];
  if (doc && typeof doc === "object") {
    const obj = doc as Record<string, unknown>;
    if (Array.isArray(obj.items)) return obj.items as CollectionDoc[];
    if (Array.isArray(obj.collections)) return obj.collections as CollectionDoc[];
  }
  throw new Error(
    "expected an array of collections, or an object with a `collections` or `items` array",
  );
}

/** `input` is either a local file path or an `http(s)://` server origin
 * (or its `/api/collections` URL directly) to fetch the live schema
 * from. */
async function loadCollections(input: string, token?: string): Promise<CollectionDoc[]> {
  let raw: string;
  if (/^https?:\/\//.test(input)) {
    const url = input.includes("/api/collections")
      ? input
      : `${input.replace(/\/+$/, "")}/api/collections?perPage=1000`;
    const headers: Record<string, string> = token ? { Authorization: `Bearer ${token}` } : {};
    const response = await fetch(url, { headers });
    if (!response.ok) {
      throw new Error(`GET ${url} failed: ${response.status} ${await response.text()}`);
    }
    raw = await response.text();
  } else {
    raw = await Bun.file(input).text();
  }
  return extractCollections(JSON.parse(raw));
}

function generate(collections: CollectionDoc[]): string {
  const nonSystem = collections.filter((c) => !c.system);
  const banner = [
    "// Generated by @cratebase/schema-codegen. Do not edit by hand;",
    "// re-run the codegen script instead.",
    "",
  ];
  const body = nonSystem.map(generateInterface).join("\n\n");
  return `${banner.join("\n")}${body}\n`;
}

interface Args {
  input: string;
  out: string;
  token?: string;
}

function parseArgs(argv: string[]): Args {
  const positional: string[] = [];
  let out = "cratebase-types.d.ts";
  let token: string | undefined;
  for (let i = 0; i < argv.length; i++) {
    const arg = argv[i];
    if (arg === "-o" || arg === "--out") {
      out = argv[++i];
    } else if (arg === "--token") {
      token = argv[++i];
    } else if (arg === "-h" || arg === "--help") {
      console.log(
        "usage: cratebase-codegen <schema.json | server-url> [-o out.d.ts] [--token <jwt>]",
      );
      process.exit(0);
    } else {
      positional.push(arg);
    }
  }
  const [input, positionalOut] = positional;
  if (!input) {
    throw new Error(
      "missing input: pass a schema-as-code JSON file path or a live server URL",
    );
  }
  return { input, out: positionalOut ?? out, token };
}

async function main() {
  const { input, out, token } = parseArgs(process.argv.slice(2));
  const collections = await loadCollections(input, token);
  const generated = generate(collections);
  await Bun.write(out, generated);
  const count = collections.filter((c) => !c.system).length;
  console.log(`wrote ${count} interface(s) to ${out}`);
}

if (import.meta.main) {
  main().catch((error) => {
    console.error(`cratebase-codegen: ${error instanceof Error ? error.message : error}`);
    process.exit(1);
  });
}

export { extractCollections, generate, generateInterface, pascalCase, tsType };
