/** `createCratebaseHooks<Schema>()` — the typed-inference entry point:
 * binds every hook in this package to `Schema` (as generated by
 * `@cratebase/schema-codegen`, or written by hand) so a collection name
 * literal infers its record type, the same way `createClient<Schema>()`
 * already does for `client.collection(name)`.
 *
 * Why a factory instead of module augmentation: module augmentation
 * (`declare module "@cratebase/react" { interface Register { schema:
 * Schema } }`) works, but only for a *single, global* schema per
 * process — awkward for tests (a schema fixture would leak across test
 * files via global augmentation) and for any app with more than one
 * Cratebase client/schema. A factory keeps the schema a normal type
 * parameter, scoped to wherever its returned hooks are imported from, at
 * the cost of one extra call site (`const { useRecords } =
 * createCratebaseHooks<Schema>();`, once, in a shared module) — the same
 * trade `zustand`'s and `jotai`'s typed-store factories make.
 *
 * The returned hooks still read the client from `<CratebaseProvider>`
 * context (or accept one explicitly, same as every hook here) — this
 * factory only narrows *types*, it does not construct or hold a client
 * itself. */

import type { AnySchema, RecordModel } from "@cratebase/client";
import { useCratebase } from "./context.js";
import { useAuth, type AuthState } from "./useAuth.js";
import { useRecords, type UseRecordsOptions, type UseRecordsResult } from "./useRecords.js";
import { useRecord, type UseRecordOptions, type UseRecordResult } from "./useRecord.js";
import {
  useInfiniteRecords,
  type UseInfiniteRecordsOptions,
  type UseInfiniteRecordsResult,
} from "./useInfiniteRecords.js";
import { useMutation, type UseMutationResult } from "./useMutation.js";
import { useSubscription, type SubscriptionEvent } from "./useSubscription.js";
import type { SubscribeOptions } from "@cratebase/client";

export function createCratebaseHooks<S extends AnySchema>() {
  return {
    /** `useCratebase()` narrowed to `S` — `client.collection(name)` infers
     * from `S` the same way it does off `createClient<S>()` directly. */
    useCratebase: () => useCratebase<S>(),

    useAuth: <U extends RecordModel = RecordModel>(): AuthState<U> => useAuth<U>(),

    useRecords: <K extends keyof S & string>(
      collectionName: K,
      options?: UseRecordsOptions<S[K] & RecordModel>,
    ): UseRecordsResult<S[K] & RecordModel> => useRecords<S[K] & RecordModel>(collectionName, options),

    useRecord: <K extends keyof S & string>(
      collectionName: K,
      id: string | null | undefined,
      options?: UseRecordOptions,
    ): UseRecordResult<S[K] & RecordModel> => useRecord<S[K] & RecordModel>(collectionName, id, options),

    useInfiniteRecords: <K extends keyof S & string>(
      collectionName: K,
      options?: UseInfiniteRecordsOptions<S[K] & RecordModel>,
    ): UseInfiniteRecordsResult<S[K] & RecordModel> =>
      useInfiniteRecords<S[K] & RecordModel>(collectionName, options),

    useMutation: <K extends keyof S & string>(collectionName: K): UseMutationResult<S[K] & RecordModel> =>
      useMutation<S[K] & RecordModel>(collectionName),

    useSubscription: <K extends keyof S & string>(
      collectionName: K,
      topic: string,
      callback: (event: SubscriptionEvent<S[K] & RecordModel>) => void,
      options?: SubscribeOptions,
    ): void => useSubscription<S[K] & RecordModel>(collectionName, topic, callback, options),
  };
}
