// Generated by `cratebase typegen`. Do not edit by hand;
// re-run `cratebase typegen` instead.
//
// This file is checked into the template so `tsc`/`next build` work right
// after scaffolding, before `cratebase dev` has ever run. Once you run
// `bun run dev` (or `npm run dev`/`pnpm dev`/`yarn dev`), `cratebase dev`
// regenerates this file from your actual schema and keeps it in sync on
// every collection change — see schema.json.

/** `users` (auth). Generated by `cratebase typegen` — do not edit by hand. */
export type UsersRecord = {
  id: string;
  tokenKey: string;
  email: string;
  emailVisibility?: boolean;
  verified?: boolean;
  name?: string;
  avatar?: string;
  readonly created?: string;
  readonly updated?: string;
};

/** `users` create input. Generated by `cratebase typegen` — do not edit by hand. */
export type UsersCreate = {
  name?: string;
  avatar?: string;
  password: string;
  passwordConfirm: string;
};

/** `users` update input — every `UsersCreate` field, optional. */
export type UsersUpdate = Partial<UsersCreate>;

/** `posts` (base). Generated by `cratebase typegen` — do not edit by hand. */
export type PostsRecord = {
  id: string;
  title: string;
  content?: string;
  owner: string;
  cover?: string;
  readonly created?: string;
  readonly updated?: string;
  expand?: {
    owner?: UsersRecord;
  };
};

/** `posts` create input. Generated by `cratebase typegen` — do not edit by hand. */
export type PostsCreate = {
  title: string;
  content?: string;
  owner: string;
  cover?: string;
};

/** `posts` update input — every `PostsCreate` field, optional. */
export type PostsUpdate = Partial<PostsCreate>;

/** Every non-system collection, keyed by name — pass to `createClient<Schema>()`. */
export type Schema = {
  users: UsersRecord;
  posts: PostsRecord;
};

export type Collections = keyof Schema;

/** `create()`/`update()` input types per collection — pass alongside `Schema` as
 * `createClient<Schema, SchemaCreate, SchemaUpdate>()`'s 2nd/3rd type params for
 * typed writes. View collections map to `never` (they can't be created or updated). */
export type SchemaCreate = {
  users: UsersCreate;
  posts: PostsCreate;
};

export type SchemaUpdate = {
  users: UsersUpdate;
  posts: PostsUpdate;
};
