//! Built-in TypeScript typegen: turns a set of collections into a single
//! `.d.ts`-shaped string with one `<Name>Record` (plus `<Name>Create`/
//! `<Name>Update` for non-view collections) interface per non-system
//! collection, and `Schema`/`Collections`/`SchemaCreate`/`SchemaUpdate`
//! exports matching what `createClient<Schema>()` in `sdk/js/client`
//! consumes.
//!
//! This supersedes `tools/schema-codegen` (still works, but is a
//! separate opt-in build step) — see that package's README. Reachable
//! from three places that all end up calling [`generate`]:
//! `cratebase typegen` (`crates/server/src/main.rs`), `GET /api/typegen`
//! (`crates/server/src/routes/typegen.rs`), and the `--dev`
//! `CB_TYPEGEN_OUT` watch (`crates/server/src/routes/collections.rs`).

use std::collections::HashMap;

use cratebase_core::{Collection, Field, FieldKind};

const BANNER: &str = "// Generated by `cratebase typegen`. Do not edit by hand;\n// re-run `cratebase typegen` instead.\n\n";

/// Generate the full `.d.ts` source for every non-system collection in
/// `collections`.
pub fn generate<'a, I>(collections: I) -> String
where
    I: IntoIterator<Item = &'a Collection>,
{
    let all: Vec<&Collection> = collections.into_iter().filter(|c| !c.system).collect();
    let by_id: HashMap<&str, &Collection> = all.iter().map(|c| (c.id.as_str(), *c)).collect();

    let mut out = String::from(BANNER);
    for c in &all {
        out.push_str(&record_interface(c, &by_id));
        out.push_str("\n\n");
        if !c.is_view() {
            out.push_str(&create_interface(c));
            out.push_str("\n\n");
            out.push_str(&update_type(c));
            out.push_str("\n\n");
        }
    }
    out.push_str(&schema_interface(&all));
    out.push_str("\n\n");
    out.push_str(&schema_create_update(&all));
    out
}

/// `posts` -> `PostsRecord`, `push-subscriptions` -> `PushSubscriptionsRecord`.
fn pascal_case(name: &str) -> String {
    let cleaned: String = name
        .chars()
        .map(|c| if c.is_ascii_alphanumeric() { c } else { ' ' })
        .collect();
    cleaned
        .split_whitespace()
        .map(|part| {
            let mut chars = part.chars();
            match chars.next() {
                Some(first) => first.to_ascii_uppercase().to_string() + chars.as_str(),
                None => String::new(),
            }
        })
        .collect()
}

/// A property key that needs no quoting is emitted bare; anything else
/// (a field named with a hyphen, say) is a quoted string literal key.
fn property_key(name: &str) -> String {
    let valid = name.starts_with(|c: char| c.is_ascii_alphabetic() || c == '_' || c == '$')
        && name
            .chars()
            .all(|c| c.is_ascii_alphanumeric() || c == '_' || c == '$');
    if valid {
        name.to_string()
    } else {
        serde_json::to_string(name).unwrap_or_else(|_| format!("{name:?}"))
    }
}

fn string_literal(value: &str) -> String {
    serde_json::to_string(value).unwrap_or_else(|_| format!("{value:?}"))
}

fn multi(base: &str, max_select: i64) -> String {
    if max_select > 1 {
        format!("{base}[]")
    } else {
        base.to_string()
    }
}

fn select_type(values: &[String], max_select: i64) -> String {
    let base = if values.is_empty() {
        "string".to_string()
    } else {
        let union = values
            .iter()
            .map(|v| string_literal(v))
            .collect::<Vec<_>>()
            .join(" | ");
        if max_select > 1 {
            format!("({union})")
        } else {
            union
        }
    };
    multi(&base, max_select)
}

/// This field's base TS type, ignoring `expand` — `None` for `password`
/// fields, which never round-trip out of a record read.
fn scalar_type(field: &Field) -> Option<String> {
    let ty = match &field.kind {
        FieldKind::Password { .. } => return None,
        FieldKind::Text { .. }
        | FieldKind::Editor { .. }
        | FieldKind::Email { .. }
        | FieldKind::Url { .. }
        | FieldKind::Date { .. }
        | FieldKind::Autodate { .. } => "string".to_string(),
        FieldKind::Number { .. } => "number".to_string(),
        FieldKind::Bool {} => "boolean".to_string(),
        FieldKind::Json { .. } => "unknown".to_string(),
        FieldKind::Vector { .. } => "number[]".to_string(),
        FieldKind::GeoPoint {} => "{ lon: number; lat: number }".to_string(),
        FieldKind::Select { values, max_select } => select_type(values, *max_select),
        FieldKind::File { max_select, .. } => multi("string", *max_select),
        FieldKind::Relation { max_select, .. } => multi("string", *max_select),
    };
    Some(ty)
}

/// `export interface <Name>Record { ... }`, including an `expand?: {...}`
/// block when the collection has any relation fields.
fn record_interface(c: &Collection, by_id: &HashMap<&str, &Collection>) -> String {
    let name = format!("{}Record", pascal_case(&c.name));
    let mut lines = vec![
        format!(
            "/** `{}` ({}). Generated by `cratebase typegen` — do not edit by hand. */",
            c.name,
            c.collection_type.as_str()
        ),
        format!("export interface {name} {{"),
    ];

    let mut relation_fields: Vec<&Field> = Vec::new();
    for field in &c.fields {
        let Some(ts) = scalar_type(field) else {
            continue;
        };
        let optional = if field.required { "" } else { "?" };
        let readonly = if matches!(field.kind, FieldKind::Autodate { .. }) {
            "readonly "
        } else {
            ""
        };
        lines.push(format!(
            "  {readonly}{}{optional}: {ts};",
            property_key(&field.name)
        ));
        if matches!(field.kind, FieldKind::Relation { .. }) {
            relation_fields.push(field);
        }
    }

    if !relation_fields.is_empty() {
        lines.push("  expand?: {".to_string());
        for field in relation_fields {
            let target_type = field
                .relation_collection_id()
                .and_then(|id| by_id.get(id))
                .map(|target| format!("{}Record", pascal_case(&target.name)))
                .unwrap_or_else(|| "Record<string, unknown>".to_string());
            let max_select = field.max_select().unwrap_or(1);
            let ty = multi(&target_type, max_select);
            lines.push(format!("    {}?: {ty};", property_key(&field.name)));
        }
        lines.push("  };".to_string());
    }

    lines.push("}".to_string());
    lines.join("\n")
}

/// `export interface <Name>Create { ... }` — system and autodate fields
/// are excluded (the server fills them in), required fields stay
/// required, and auth collections get an explicit `password`/
/// `passwordConfirm` pair (the underlying `password` field is itself
/// `system`, so it would otherwise be dropped by the same rule).
fn create_interface(c: &Collection) -> String {
    let name = format!("{}Create", pascal_case(&c.name));
    let mut lines = vec![
        format!(
            "/** `{}` create input. Generated by `cratebase typegen` — do not edit by hand. */",
            c.name
        ),
        format!("export interface {name} {{"),
    ];
    for field in &c.fields {
        if field.system || matches!(field.kind, FieldKind::Autodate { .. }) {
            continue;
        }
        let Some(ts) = scalar_type(field) else {
            continue;
        };
        let optional = if field.required { "" } else { "?" };
        lines.push(format!("  {}{optional}: {ts};", property_key(&field.name)));
    }
    if c.is_auth() {
        lines.push("  password: string;".to_string());
        lines.push("  passwordConfirm: string;".to_string());
    }
    lines.push("}".to_string());
    lines.join("\n")
}

/// `export type <Name>Update = Partial<<Name>Create>;`
fn update_type(c: &Collection) -> String {
    let pascal = pascal_case(&c.name);
    format!(
        "/** `{}` update input — every `{pascal}Create` field, optional. */\nexport type {pascal}Update = Partial<{pascal}Create>;",
        c.name
    )
}

/// Every non-system collection, keyed by name, typed to its own
/// `<Name>Record` interface — pass to `createClient<Schema>()` for a
/// typed `client.collection(name)`.
fn schema_interface(all: &[&Collection]) -> String {
    let mut lines = vec![
        "/** Every non-system collection, keyed by name — pass to `createClient<Schema>()`. */"
            .to_string(),
        "export interface Schema {".to_string(),
    ];
    for c in all {
        lines.push(format!(
            "  {}: {}Record;",
            property_key(&c.name),
            pascal_case(&c.name)
        ));
    }
    lines.push("}".to_string());
    lines.push(String::new());
    lines.push("export type Collections = keyof Schema;".to_string());
    lines.join("\n")
}

/// `SchemaCreate`/`SchemaUpdate`: the same keys as `Schema`, typed to
/// each collection's own `<Name>Create`/`<Name>Update` — pass alongside
/// `Schema` as `createClient<Schema, SchemaCreate, SchemaUpdate>()`'s
/// 2nd/3rd type params for `create()`/`update()` calls typed to the
/// collection's actual input shape instead of `Partial<Record>`. View
/// collections (which can't be created or updated) map to `never`.
fn schema_create_update(all: &[&Collection]) -> String {
    let mut lines = vec![
        "/** `create()`/`update()` input types per collection — pass alongside `Schema` as".to_string(),
        " * `createClient<Schema, SchemaCreate, SchemaUpdate>()`'s 2nd/3rd type params for".to_string(),
        " * typed writes. View collections map to `never` (they can't be created or updated). */".to_string(),
        "export interface SchemaCreate {".to_string(),
    ];
    for c in all {
        let ty = if c.is_view() {
            "never".to_string()
        } else {
            format!("{}Create", pascal_case(&c.name))
        };
        lines.push(format!("  {}: {ty};", property_key(&c.name)));
    }
    lines.push("}".to_string());
    lines.push(String::new());
    lines.push("export interface SchemaUpdate {".to_string());
    for c in all {
        let ty = if c.is_view() {
            "never".to_string()
        } else {
            format!("{}Update", pascal_case(&c.name))
        };
        lines.push(format!("  {}: {ty};", property_key(&c.name)));
    }
    lines.push("}".to_string());
    lines.join("\n")
}

#[cfg(test)]
mod tests {
    use super::*;
    use cratebase_core::field::EmbeddingConfig;
    use cratebase_core::CollectionType;

    fn field(name: &str, kind: FieldKind) -> Field {
        Field::new(name, kind)
    }

    fn text(name: &str) -> Field {
        field(
            name,
            FieldKind::Text {
                min: 0,
                max: 0,
                pattern: String::new(),
                autogenerate_pattern: String::new(),
                primary_key: false,
            },
        )
    }

    /// A base collection covering every field type, to exercise the
    /// mapping in one pass.
    fn every_field_type_collection() -> Collection {
        let mut c = Collection::new("widgets", CollectionType::Base);
        let mut title = text("title");
        title.required = true;
        let body = field(
            "body",
            FieldKind::Editor {
                max_size: 0,
                convert_urls: false,
            },
        );
        let mut count = field(
            "count",
            FieldKind::Number {
                min: None,
                max: None,
                only_int: true,
            },
        );
        count.required = true;
        let active = field("active", FieldKind::Bool {});
        let contact = field(
            "contact",
            FieldKind::Email {
                except_domains: vec![],
                only_domains: vec![],
            },
        );
        let site = field(
            "site",
            FieldKind::Url {
                except_domains: vec![],
                only_domains: vec![],
            },
        );
        let when = field(
            "when",
            FieldKind::Date {
                min: None,
                max: None,
            },
        );
        let tag = field(
            "tag",
            FieldKind::Select {
                values: vec!["a".into(), "b".into()],
                max_select: 1,
            },
        );
        let mut tags = field(
            "tags",
            FieldKind::Select {
                values: vec!["a".into(), "b".into()],
                max_select: 2,
            },
        );
        tags.required = true;
        let photo = field(
            "photo",
            FieldKind::File {
                max_select: 1,
                max_size: 0,
                mime_types: vec![],
                thumbs: vec![],
                protected: false,
            },
        );
        let gallery = field(
            "gallery",
            FieldKind::File {
                max_select: 5,
                max_size: 0,
                mime_types: vec![],
                thumbs: vec![],
                protected: false,
            },
        );
        let meta = field("meta", FieldKind::Json { max_size: 0 });
        let loc = field("loc", FieldKind::GeoPoint {});
        let embedding = field(
            "embedding",
            FieldKind::Vector {
                dimensions: 3,
                embedding: Some(EmbeddingConfig {
                    provider: "echo".into(),
                    model: String::new(),
                    source_field: "body".into(),
                }),
            },
        );
        let pos = c.fields.len() - 2;
        c.fields.splice(
            pos..pos,
            [
                title, body, count, active, contact, site, when, tag, tags, photo, gallery, meta,
                loc, embedding,
            ],
        );
        c
    }

    #[test]
    fn maps_every_scalar_field_type() {
        let c = every_field_type_collection();
        let out = generate([&c]);
        assert!(out.contains("export interface WidgetsRecord {"));
        assert!(out.contains("title: string;"));
        assert!(out.contains("body?: string;"));
        assert!(out.contains("count: number;"));
        assert!(out.contains("active?: boolean;"));
        assert!(out.contains("contact?: string;"));
        assert!(out.contains("site?: string;"));
        assert!(out.contains("when?: string;"));
        assert!(out.contains("meta?: unknown;"));
        assert!(out.contains("loc?: { lon: number; lat: number };"));
        assert!(out.contains("embedding?: number[];"));
        assert!(out.contains("readonly created?: string;"));
        assert!(out.contains("readonly updated?: string;"));
    }

    #[test]
    fn select_fields_become_string_literal_unions() {
        let c = every_field_type_collection();
        let out = generate([&c]);
        assert!(out.contains(r#"tag?: "a" | "b";"#));
        assert!(out.contains(r#"tags: ("a" | "b")[];"#));
    }

    #[test]
    fn file_fields_are_single_or_array_by_max_select() {
        let c = every_field_type_collection();
        let out = generate([&c]);
        assert!(out.contains("photo?: string;"));
        assert!(out.contains("gallery?: string[];"));
    }

    #[test]
    fn relation_fields_are_ids_plus_a_typed_expand_block() {
        let mut authors = Collection::new("authors", CollectionType::Base);
        let mut posts = Collection::new("posts", CollectionType::Base);
        let mut author_ref = field(
            "author",
            FieldKind::Relation {
                collection_id: authors.id.clone(),
                cascade_delete: false,
                min_select: 0,
                max_select: 1,
            },
        );
        author_ref.required = true;
        let tags_ref = field(
            "coauthors",
            FieldKind::Relation {
                collection_id: authors.id.clone(),
                cascade_delete: false,
                min_select: 0,
                max_select: 5,
            },
        );
        let pos = posts.fields.len() - 2;
        posts.fields.splice(pos..pos, [author_ref, tags_ref]);
        let _ = &mut authors;

        let out = generate([&authors, &posts]);
        assert!(out.contains("author: string;"));
        assert!(out.contains("coauthors?: string[];"));
        assert!(out.contains("expand?: {"));
        assert!(out.contains("author?: AuthorsRecord;"));
        assert!(out.contains("coauthors?: AuthorsRecord[];"));
    }

    #[test]
    fn relation_to_an_unexported_collection_falls_back_to_a_generic_record() {
        let mut posts = Collection::new("posts", CollectionType::Base);
        let mut owner = field(
            "owner",
            FieldKind::Relation {
                collection_id: "some_missing_id".into(),
                cascade_delete: false,
                min_select: 0,
                max_select: 1,
            },
        );
        owner.required = true;
        let pos = posts.fields.len() - 2;
        posts.fields.insert(pos, owner);

        let out = generate([&posts]);
        assert!(out.contains("owner?: Record<string, unknown>;"));
    }

    #[test]
    fn password_fields_are_excluded_from_the_record_type() {
        let users = Collection::default_users();
        let out = generate([&users]);
        let record_start = out.find("export interface UsersRecord {").unwrap();
        let record_end = record_start + out[record_start..].find("\n}").unwrap();
        let record_block = &out[record_start..record_end];
        assert!(!record_block.contains("password"));
    }

    #[test]
    fn auth_collections_expose_email_visibility_verified_and_have_password_create_fields() {
        let users = Collection::default_users();
        let out = generate([&users]);
        assert!(out.contains("email: string;"));
        assert!(out.contains("emailVisibility?: boolean;"));
        assert!(out.contains("verified?: boolean;"));
        assert!(out.contains("export interface UsersCreate {"));
        assert!(out.contains("password: string;"));
        assert!(out.contains("passwordConfirm: string;"));
    }

    #[test]
    fn create_excludes_system_and_autodate_fields_and_respects_required() {
        let c = every_field_type_collection();
        let out = generate([&c]);
        let create_start = out.find("export interface WidgetsCreate {").unwrap();
        let create_block = &out[create_start..];
        let create_end = create_block.find("\n}").unwrap();
        let create_block = &create_block[..create_end];
        assert!(!create_block.contains("\n  id"));
        assert!(!create_block.contains("\n  created"));
        assert!(!create_block.contains("\n  updated"));
        assert!(create_block.contains("title: string;"));
        assert!(create_block.contains("count: number;"));
        assert!(create_block.contains("body?: string;"));
    }

    #[test]
    fn update_is_a_partial_of_create() {
        let c = every_field_type_collection();
        let out = generate([&c]);
        assert!(out.contains("export type WidgetsUpdate = Partial<WidgetsCreate>;"));
    }

    #[test]
    fn view_collections_only_get_a_record_type() {
        let mut c = Collection::new("active_users", CollectionType::View);
        c.view_query = "select id from users".into();
        let out = generate([&c]);
        assert!(out.contains("export interface ActiveUsersRecord {"));
        assert!(!out.contains("ActiveUsersCreate"));
        assert!(!out.contains("ActiveUsersUpdate"));
        assert!(out.contains("active_users: ActiveUsersRecord;"));
        assert!(out.contains("active_users: never;"));
    }

    #[test]
    fn system_collections_are_never_generated() {
        let c = Collection::new("posts", CollectionType::Base);
        let sys = Collection::default_superusers();
        let out = generate([&c, &sys]);
        assert!(!out.contains("Superusers"));
    }

    #[test]
    fn schema_and_collections_exports_cover_every_generated_collection() {
        let posts = Collection::new("posts", CollectionType::Base);
        let out = generate([&posts]);
        assert!(out.contains("export interface Schema {"));
        assert!(out.contains("posts: PostsRecord;"));
        assert!(out.contains("export type Collections = keyof Schema;"));
        assert!(out.contains("export interface SchemaCreate {"));
        assert!(out.contains("posts: PostsCreate;"));
        assert!(out.contains("export interface SchemaUpdate {"));
        assert!(out.contains("posts: PostsUpdate;"));
    }

    #[test]
    fn hyphenated_collection_and_field_names_get_quoted_keys() {
        let mut c = Collection::new("push-subscriptions", CollectionType::Base);
        let f = text("device-id");
        let pos = c.fields.len() - 2;
        c.fields.insert(pos, f);
        let out = generate([&c]);
        assert!(out.contains("export interface PushSubscriptionsRecord {"));
        assert!(out.contains(r#""device-id"?: string;"#));
        assert!(out.contains(r#""push-subscriptions": PushSubscriptionsRecord;"#));
    }
}
