// Type declarations for the Cratebase JavaScript runtime (pb_hooks).
// Generated by cratebase; reference it from your hook files with
//   /// <reference path="../pb_data/types.d.ts" />

// ---------------------------------------------------------------------------
// Errors
// ---------------------------------------------------------------------------

declare class ApiError extends Error {
  constructor(status?: number, message?: string, data?: Record<string, any>);
  status: number;
  data: Record<string, any>;
  isApiError: true;
}
declare class BadRequestError extends ApiError {
  constructor(message?: string, data?: Record<string, any>);
}
declare class UnauthorizedError extends ApiError {
  constructor(message?: string, data?: Record<string, any>);
}
declare class ForbiddenError extends ApiError {
  constructor(message?: string, data?: Record<string, any>);
}
declare class NotFoundError extends ApiError {
  constructor(message?: string, data?: Record<string, any>);
}
declare class TooManyRequestsError extends ApiError {
  constructor(message?: string, data?: Record<string, any>);
}
declare class InternalServerError extends ApiError {
  constructor(message?: string, data?: Record<string, any>);
}

// ---------------------------------------------------------------------------
// Models
// ---------------------------------------------------------------------------

interface FieldDef {
  id?: string;
  name: string;
  type: string;
  system?: boolean;
  hidden?: boolean;
  presentable?: boolean;
  required?: boolean;
  [option: string]: any;
}

interface FieldList extends Array<FieldDef> {
  getByName(name: string): FieldDef | null;
  getById(id: string): FieldDef | null;
  add(...fields: FieldDef[]): void;
  removeByName(name: string): void;
}

declare class Collection {
  constructor(data?: Partial<CollectionData>);
  id: string;
  name: string;
  type: "base" | "auth" | "view";
  system: boolean;
  fields: FieldList;
  indexes: string[];
  listRule: string | null;
  viewRule: string | null;
  createRule: string | null;
  updateRule: string | null;
  deleteRule: string | null;
  created: string;
  updated: string;
  viewQuery?: string;
  authRule?: string | null;
  manageRule?: string | null;
  [option: string]: any;
  isAuth(): boolean;
  isBase(): boolean;
  isView(): boolean;
  toJSON(): CollectionData;
}
type CollectionData = { [key: string]: any };

declare class DateTime {
  constructor(value?: string | number | Date);
  time(): Date;
  unix(): number;
  isZero(): boolean;
  string(): string;
}

/** A file to attach to a record field (see $filesystem). */
interface FileMarker {
  __file: { path?: string; bytes?: number[]; url?: string; name: string };
}

declare class Record {
  constructor(collection?: Collection, data?: { [field: string]: any });
  id: string;
  readonly collectionId: string;
  readonly collectionName: string;
  isNew(): boolean;
  collection(): Collection;
  get(field: string): any;
  getRaw(field: string): any;
  set(field: string, value: any): void;
  load(data: { [field: string]: any }): void;
  getString(field: string): string;
  getBool(field: string): boolean;
  getInt(field: string): number;
  getFloat(field: string): number;
  getDateTime(field: string): DateTime;
  getStringSlice(field: string): string[];
  getUnsavedFiles(field: string): FileMarker[];
  original(): Record;
  fresh(): Record;
  clone(): Record;
  expand(): { [rel: string]: any };
  setExpand(map: { [rel: string]: any }): void;
  mergeExpand(map: { [rel: string]: any }): void;
  expandedOne(rel: string): Record | null;
  expandedAll(rel: string): Record[];
  email(): string;
  setEmail(email: string): void;
  verified(): boolean;
  setVerified(v: boolean): void;
  emailVisibility(): boolean;
  setEmailVisibility(v: boolean): void;
  tokenKey(): string;
  setTokenKey(key: string): void;
  refreshTokenKey(): void;
  setPassword(password: string): void;
  validatePassword(password: string): boolean;
  hide(...fields: string[]): void;
  unhide(...fields: string[]): void;
  publicExport(): { [field: string]: any };
  toJSON(): { [field: string]: any };
}

// ---------------------------------------------------------------------------
// Events
// ---------------------------------------------------------------------------

interface RequestInfo {
  method: string;
  query: { [key: string]: any };
  headers: { [key: string]: any };
  body: any;
  auth: Record | null;
  context: string;
}

interface Request {
  method: string;
  headers: { [name: string]: string };
  url: { path: string; query(): { get(name: string): string }; string(): string };
  pathValue(name: string): string;
  header: { get(name: string): string };
  body: any;
  /** Exact request body bytes (lossy UTF-8), before JSON parsing. Use this,
   * never `body`, to verify an HMAC webhook signature (Stripe, Tripay,
   * GitHub, ...) — parsing then re-stringifying `body` does not reproduce
   * the sender's exact bytes and every real signature check will fail. */
  rawBody: string;
  remoteAddr: string;
}

interface Response {
  header(name: string, value?: string): string;
  headers: { [name: string]: string };
}

interface BaseEvent {
  app: typeof $app;
  next(): void;
  get(key: string): any;
  set(key: string, value: any): void;
  [key: string]: any;
}

interface RecordEvent extends BaseEvent {
  record: Record;
  collection?: Collection;
}

interface CollectionEvent extends BaseEvent {
  collection: Collection;
}

interface RequestEvent extends BaseEvent {
  auth: Record | null;
  request: Request;
  response: Response;
  requestInfo(): RequestInfo;
  hasSuperuserAuth(): boolean;
  realIP(): string;
  json(status: number, body: any): void;
  string(status: number, text: string): void;
  html(status: number, html: string): void;
  blob(status: number, contentType: string, bytes: number[] | string | Uint8Array): void;
  redirect(status: number, url: string): void;
  noContent(status?: number): void;
  error(status: number, message?: string, data?: any): ApiError;
  badRequestError(message?: string, data?: any): BadRequestError;
  notFoundError(message?: string, data?: any): NotFoundError;
  forbiddenError(message?: string, data?: any): ForbiddenError;
  unauthorizedError(message?: string, data?: any): UnauthorizedError;
  tooManyRequestsError(message?: string, data?: any): TooManyRequestsError;
  internalServerError(message?: string, data?: any): InternalServerError;
}

interface RecordRequestEvent extends RequestEvent {
  record: Record;
  collection: Collection;
}

interface MailerEvent extends BaseEvent {
  message: { from?: any; to: any[]; subject: string; html: string; text?: string };
  record?: Record;
}

type HookHandler<E> = (e: E) => void;
type Middleware = ((e: RequestEvent) => void) | { id: string; func: (e: RequestEvent) => void };

// ---------------------------------------------------------------------------
// Registration functions
// ---------------------------------------------------------------------------

declare function onBootstrap(handler: HookHandler<BaseEvent>): string;
declare function onServe(handler: HookHandler<BaseEvent>): string;
declare function onTerminate(handler: HookHandler<BaseEvent>): string;

declare function onRecordEnrich(handler: HookHandler<RecordEvent>, ...tags: string[]): string;
declare function onRecordValidate(handler: HookHandler<RecordEvent>, ...tags: string[]): string;
declare function onRecordCreate(handler: HookHandler<RecordEvent>, ...tags: string[]): string;
declare function onRecordCreateExecute(handler: HookHandler<RecordEvent>, ...tags: string[]): string;
declare function onRecordAfterCreateSuccess(handler: HookHandler<RecordEvent>, ...tags: string[]): string;
declare function onRecordAfterCreateError(handler: HookHandler<RecordEvent>, ...tags: string[]): string;
declare function onRecordUpdate(handler: HookHandler<RecordEvent>, ...tags: string[]): string;
declare function onRecordUpdateExecute(handler: HookHandler<RecordEvent>, ...tags: string[]): string;
declare function onRecordAfterUpdateSuccess(handler: HookHandler<RecordEvent>, ...tags: string[]): string;
declare function onRecordAfterUpdateError(handler: HookHandler<RecordEvent>, ...tags: string[]): string;
declare function onRecordDelete(handler: HookHandler<RecordEvent>, ...tags: string[]): string;
declare function onRecordDeleteExecute(handler: HookHandler<RecordEvent>, ...tags: string[]): string;
declare function onRecordAfterDeleteSuccess(handler: HookHandler<RecordEvent>, ...tags: string[]): string;
declare function onRecordAfterDeleteError(handler: HookHandler<RecordEvent>, ...tags: string[]): string;

declare function onRecordCreateRequest(handler: HookHandler<RecordRequestEvent>, ...tags: string[]): string;
declare function onRecordUpdateRequest(handler: HookHandler<RecordRequestEvent>, ...tags: string[]): string;
declare function onRecordDeleteRequest(handler: HookHandler<RecordRequestEvent>, ...tags: string[]): string;
declare function onRecordListRequest(handler: HookHandler<RequestEvent>, ...tags: string[]): string;
declare function onRecordViewRequest(handler: HookHandler<RecordRequestEvent>, ...tags: string[]): string;

declare function onCollectionValidate(handler: HookHandler<CollectionEvent>, ...tags: string[]): string;
declare function onCollectionCreate(handler: HookHandler<CollectionEvent>, ...tags: string[]): string;
declare function onCollectionCreateExecute(handler: HookHandler<CollectionEvent>, ...tags: string[]): string;
declare function onCollectionAfterCreateSuccess(handler: HookHandler<CollectionEvent>, ...tags: string[]): string;
declare function onCollectionAfterCreateError(handler: HookHandler<CollectionEvent>, ...tags: string[]): string;
declare function onCollectionUpdate(handler: HookHandler<CollectionEvent>, ...tags: string[]): string;
declare function onCollectionUpdateExecute(handler: HookHandler<CollectionEvent>, ...tags: string[]): string;
declare function onCollectionAfterUpdateSuccess(handler: HookHandler<CollectionEvent>, ...tags: string[]): string;
declare function onCollectionAfterUpdateError(handler: HookHandler<CollectionEvent>, ...tags: string[]): string;
declare function onCollectionDelete(handler: HookHandler<CollectionEvent>, ...tags: string[]): string;
declare function onCollectionDeleteExecute(handler: HookHandler<CollectionEvent>, ...tags: string[]): string;
declare function onCollectionAfterDeleteSuccess(handler: HookHandler<CollectionEvent>, ...tags: string[]): string;
declare function onCollectionAfterDeleteError(handler: HookHandler<CollectionEvent>, ...tags: string[]): string;
declare function onCollectionCreateRequest(handler: HookHandler<RequestEvent & CollectionEvent>, ...tags: string[]): string;
declare function onCollectionUpdateRequest(handler: HookHandler<RequestEvent & CollectionEvent>, ...tags: string[]): string;
declare function onCollectionDeleteRequest(handler: HookHandler<RequestEvent & CollectionEvent>, ...tags: string[]): string;
declare function onCollectionsListRequest(handler: HookHandler<RequestEvent>): string;
declare function onCollectionViewRequest(handler: HookHandler<RequestEvent & CollectionEvent>, ...tags: string[]): string;
declare function onCollectionsImportRequest(handler: HookHandler<RequestEvent>): string;

declare function onRecordAuthRequest(handler: HookHandler<RecordRequestEvent>, ...tags: string[]): string;
declare function onRecordAuthWithPasswordRequest(handler: HookHandler<RecordRequestEvent>, ...tags: string[]): string;
declare function onRecordAuthWithOAuth2Request(handler: HookHandler<RecordRequestEvent>, ...tags: string[]): string;
declare function onRecordAuthWithOTPRequest(handler: HookHandler<RecordRequestEvent>, ...tags: string[]): string;
declare function onRecordAuthRefreshRequest(handler: HookHandler<RecordRequestEvent>, ...tags: string[]): string;
declare function onRecordRequestOTPRequest(handler: HookHandler<RecordRequestEvent>, ...tags: string[]): string;
declare function onRecordRequestPasswordResetRequest(handler: HookHandler<RecordRequestEvent>, ...tags: string[]): string;
declare function onRecordConfirmPasswordResetRequest(handler: HookHandler<RecordRequestEvent>, ...tags: string[]): string;
declare function onRecordRequestVerificationRequest(handler: HookHandler<RecordRequestEvent>, ...tags: string[]): string;
declare function onRecordConfirmVerificationRequest(handler: HookHandler<RecordRequestEvent>, ...tags: string[]): string;
declare function onRecordRequestEmailChangeRequest(handler: HookHandler<RecordRequestEvent>, ...tags: string[]): string;
declare function onRecordConfirmEmailChangeRequest(handler: HookHandler<RecordRequestEvent>, ...tags: string[]): string;

declare function onMailerSend(handler: HookHandler<MailerEvent>): string;
declare function onMailerRecordVerificationSend(handler: HookHandler<MailerEvent>, ...tags: string[]): string;
declare function onMailerRecordPasswordResetSend(handler: HookHandler<MailerEvent>, ...tags: string[]): string;
declare function onMailerRecordEmailChangeSend(handler: HookHandler<MailerEvent>, ...tags: string[]): string;
declare function onMailerRecordOTPSend(handler: HookHandler<MailerEvent>, ...tags: string[]): string;
declare function onMailerRecordAuthAlertSend(handler: HookHandler<MailerEvent>, ...tags: string[]): string;

declare function onRealtimeConnectRequest(handler: HookHandler<RequestEvent>): string;
declare function onRealtimeSubscribeRequest(handler: HookHandler<RequestEvent>): string;
declare function onRealtimeMessageSend(handler: HookHandler<BaseEvent>): string;

declare function onFileDownloadRequest(handler: HookHandler<RecordRequestEvent>, ...tags: string[]): string;
declare function onFileTokenRequest(handler: HookHandler<RequestEvent>, ...tags: string[]): string;

declare function onBackupCreate(handler: HookHandler<BaseEvent>): string;
declare function onBackupRestore(handler: HookHandler<BaseEvent>): string;

declare function onSettingsListRequest(handler: HookHandler<RequestEvent>): string;
declare function onSettingsUpdateRequest(handler: HookHandler<RequestEvent>): string;
declare function onSettingsReload(handler: HookHandler<BaseEvent>): string;

declare function onBatchRequest(handler: HookHandler<RequestEvent>): string;

declare function routerAdd(
  method: "GET" | "POST" | "PUT" | "PATCH" | "DELETE" | "HEAD" | "OPTIONS" | string,
  path: string,
  handler: (e: RequestEvent) => void,
  ...middlewares: Middleware[]
): string;
declare function routerUse(...middlewares: Middleware[]): void;
declare function cronAdd(id: string, cronExpr: string, handler: () => void): void;
declare function cronRemove(id: string): void;
declare function migrate(up: (app: typeof $app) => void, down?: (app: typeof $app) => void): void;

// ---------------------------------------------------------------------------
// Globals
// ---------------------------------------------------------------------------

declare const __hooks: string;

declare function require(module: string): any;
declare function sleep(milliseconds: number): void;
declare function toString(value: any): string;
declare function readerToString(value: any): string;
declare function toBytes(value: any): number[];

declare namespace console {
  function log(...args: any[]): void;
  function info(...args: any[]): void;
  function warn(...args: any[]): void;
  function error(...args: any[]): void;
  function debug(...args: any[]): void;
}

interface Logger {
  debug(message: string, ...keyValuePairs: any[]): void;
  info(message: string, ...keyValuePairs: any[]): void;
  warn(message: string, ...keyValuePairs: any[]): void;
  error(message: string, ...keyValuePairs: any[]): void;
}

interface MailMessage {
  from?: { address: string; name?: string };
  to: Array<{ address: string; name?: string } | string> | { address: string; name?: string } | string;
  subject: string;
  html?: string;
  text?: string;
  headers?: { [name: string]: string };
}

interface DbxExpression {
  __dbx: string;
  [key: string]: any;
}

declare const $app: {
  settings(): { [key: string]: any };
  findCollectionByNameOrId(nameOrId: string): Collection;
  findRecordById(collection: string | Collection, id: string): Record;
  findRecordsByFilter(
    collection: string | Collection,
    filter: string,
    sort?: string,
    limit?: number,
    offset?: number,
    params?: { [key: string]: any }
  ): Record[];
  findFirstRecordByFilter(collection: string | Collection, filter: string, params?: { [key: string]: any }): Record;
  findFirstRecordByData(collection: string | Collection, key: string, value: any): Record;
  findAllRecords(collection: string | Collection, ...expressions: Array<string | DbxExpression>): Record[];
  findAuthRecordByEmail(collection: string | Collection, email: string): Record;
  countRecords(collection: string | Collection, ...expressions: Array<string | DbxExpression>): number;
  save(model: Record | Collection): void;
  saveNoValidate(model: Record | Collection): void;
  delete(model: Record | Collection): void;
  runInTransaction(fn: (txApp: typeof $app) => void): void;
  newMailClient(): { send(message: MailMessage): void };
  logger(): Logger;
  store(): { get(key: string): any; set(key: string, value: any): void; has(key: string): boolean; remove(key: string): void };
  cron(): { add(id: string, expr: string, fn: () => void): void; remove(id: string): void };
  dao(): typeof $app;
  isBootstrapped(): boolean;
  isDev(): boolean;
};

declare const $http: {
  send(config: {
    url: string;
    method?: string;
    body?: string | number[] | { [key: string]: any };
    headers?: { [name: string]: string };
    timeout?: number;
  }): { statusCode: number; headers: { [name: string]: string }; raw: string; body: string; json: any; cookies: {} };
};

declare const $os: {
  getenv(name: string): string;
  readFile(path: string): string;
  writeFile(path: string, data: string): void;
  exists(path: string): boolean;
  tempDir(): string;
  getwd(): string;
  args(): string[];
  exit(code?: number): void;
  exec(...args: any[]): never;
};

declare const $security: {
  randomString(length: number): string;
  randomStringWithAlphabet(length: number, alphabet: string): string;
  pseudorandomString(length: number): string;
  pseudorandomStringWithAlphabet(length: number, alphabet: string): string;
  sha256(data: string): string;
  sha512(data: string): string;
  sha1(data: string): string;
  md5(data: string): string;
  hs256(data: string, secret: string): string;
  hs512(data: string, secret: string): string;
  createJWT(payload: { [claim: string]: any }, key: string, secondsDuration?: number, alg?: "HS256" | "HS512"): string;
  parseUnverifiedJWT(token: string): { [claim: string]: any };
  parseJWT(token: string, key: string): { [claim: string]: any };
  encrypt(data: string, key: string): string;
  decrypt(cipherText: string, key: string): string;
  equal(a: string, b: string): boolean;
};

declare const $tokens: {
  recordAuthToken(app: typeof $app, record: Record): string;
  recordVerifyToken(app: typeof $app, record: Record): string;
  recordResetPasswordToken(app: typeof $app, record: Record): string;
  recordChangeEmailToken(app: typeof $app, record: Record): string;
  recordFileToken(app: typeof $app, record: Record): string;
};

declare const $mails: {
  sendRecordVerification(app: typeof $app, record: Record): void;
  sendRecordPasswordReset(app: typeof $app, record: Record): void;
  sendRecordChangeEmail(app: typeof $app, record: Record): void;
  sendRecordOTP(app: typeof $app, record: Record): void;
};

declare const $filesystem: {
  fileFromPath(path: string, name?: string): FileMarker;
  fileFromBytes(bytes: number[] | Uint8Array | string, name?: string): FileMarker;
  fileFromURL(url: string, name?: string): FileMarker;
};

declare const $apis: {
  requireAuth(...collections: string[]): Middleware;
  requireSuperuserAuth(): Middleware;
  requireSuperuserOrOwnerAuth(pathParam?: string): Middleware;
  requireGuestOnly(): Middleware;
  gzip(): Middleware;
  bodyLimit(bytes?: number): Middleware;
  skipSuccessActivityLog(): Middleware;
  enrichRecord(e: RequestEvent, record: Record): Record;
  enrichRecords(e: RequestEvent, records: Record[]): Record[];
  toApiError(err: any): ApiError;
};

declare const $dbx: {
  exp(sql: string, params?: { [key: string]: any }): DbxExpression;
  hashExp(pairs: { [column: string]: any }): DbxExpression;
  and(...expressions: Array<string | DbxExpression>): DbxExpression;
  or(...expressions: Array<string | DbxExpression>): DbxExpression;
  not(expression: DbxExpression): DbxExpression;
  in(column: string, ...values: any[]): DbxExpression;
  notIn(column: string, ...values: any[]): DbxExpression;
  like(column: string, ...values: string[]): DbxExpression;
  notLike(column: string, ...values: string[]): DbxExpression;
  between(column: string, from: any, to: any): DbxExpression;
};
